# Generated by Django 2.2.3 on 2019-07-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_lead_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='author',
            field=models.CharField(default='SOME AUTHOR', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='discrition',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_hot_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(default='SOME BOOK NAME', max_length=100),
        ),
    ]
