# Generated by Django 2.2.3 on 2019-07-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20190721_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Book',
        ),
    ]
