# Generated by Django 2.2.3 on 2019-07-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20190731_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sold_out',
            new_name='is_sold_out',
        ),
    ]
