export const GET_BOOKS = "GET_BOOKS";
export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_HOOT_BOOKS = "GET_HOOT_BOOKS";
export const GET_BOOKS_BY_GENRES = "GET_BOOKS_BY_GENRES";
export const SORT_BOOKS_BY_PRICE = "SORT_BOOKS_BY_PRICE";
export const SORT_BOOKS_BY_PAGES = "SORT_BOOKS_BY_PAGES";
export const SEARCH_BOOKS = "SEARCH_BOOKS";
export const GET_BOOK_BY_ID = "GET_BOOK_BY_ID";


//SLIDER TYPES
export const GET_NEXT_SLIDE = "GET_NEXT_SLIDE";
export const GET_PREV_SLIDE = "GET_PREV_SLIDE";


//PAGINATOR TYPES
export const GET_NEXT_PAGE = "GET_NEXT_PAGE";
export const GET_PREV_PAGE = "GET_PREV_PAGE";
export const JUMP_TO_PAGE = "JUMP_TO_PAGE";
export const RESET_PAGINATOR = "RESET_PAGINATOR";


//AUTHENTICATION TYPES
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


//USER OPOTUNYTIS
export const CREATE_NEW_BOOK = "CREATE_NEW_BOOK";
export const GET_USER_BOOKS = "GET_USER_BOOKS";
export const DELETE_BOOK = "DELETE_BOOK";
export const BOOK_CREATION_FAIL = "BOOK_CREATION_FAIL";
export const NEW_CUSTOMER = "NEW_CUSTOMER";
export const CUSTOMER_BOOKS = "CUSTOMER_BOOKS";
export const PURCASED_BOOKS = "PURCASED_BOOKS";
export const APPROVE_SALE = "APPROVE_SALE";
export const USER_SOLD_BOOKS = "USER_SOLD_BOOKS";
export const CENCEL_PURCHASE = "CENCEL_PURCHASE";

