export const GET_BOOKS = "GET_BOOKS";
export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_HOOT_BOOKS = "GET_HOOT_BOOKS";
export const GET_BOOKS_BY_GENRES = "GET_BOOKS_BY_GENRES";
export const SORT_BOOKS_BY_PRICE = "SORT_BOOKS_BY_PRICE";
export const SORT_BOOKS_BY_PAGES = "SORT_BOOKS_BY_PAGES";
export const SEARCH_BOOKS = "SEARCH_BOOKS";

//SLIDER TYPES
export const GET_NEXT_SLIDE = "GET_NEXT_SLIDE";
export const GET_PREV_SLIDE = "GET_PREV_SLIDE";



